{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2a3becbd-d3cf-4701-bc68-4b1e6d9e3630",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   Ranks                                     Name  \\\n",
      "0      1                                   Amazon   \n",
      "1      2                                  Walmart   \n",
      "2      3          State Grid Corporation of China   \n",
      "3      4                             Saudi Aramco   \n",
      "4      5     China National Petroleum Corporation   \n",
      "5      6          China Petrochemical Corporation   \n",
      "6      7                                    Apple   \n",
      "7      8                                 Alphabet   \n",
      "8      9                       UnitedHealth Group   \n",
      "9     10                       Berkshire Hathaway   \n",
      "10    11                               CVS Health   \n",
      "11    12                         Volkswagen Group   \n",
      "12    13                               ExxonMobil   \n",
      "13    14                                    Vitol   \n",
      "14    15                                    Shell   \n",
      "15    16     China State Construction Engineering   \n",
      "16    17                                   Toyota   \n",
      "17    18                                 McKesson   \n",
      "18    19                                Microsoft   \n",
      "19    20                                  Cencora   \n",
      "20    21                                Trafigura   \n",
      "21    22                                   Costco   \n",
      "22    23                           JPMorgan Chase   \n",
      "23    24  Industrial and Commercial Bank of China   \n",
      "24    25                           Schwarz Gruppe   \n",
      "25    26                            TotalEnergies   \n",
      "26    27                                 Glencore   \n",
      "27    28                                   Nvidia   \n",
      "28    29                                       BP   \n",
      "29    30                          Cardinal Health   \n",
      "30    31                               Stellantis   \n",
      "31    32                                  Chevron   \n",
      "32    33                  China Construction Bank   \n",
      "33    34                      Samsung Electronics   \n",
      "34    35                                  Foxconn   \n",
      "35    36                                    Cigna   \n",
      "36    37               Agricultural Bank of China   \n",
      "37    38    China Railway Engineering Corporation   \n",
      "38    39                                  Cargill   \n",
      "39    40                       Ford Motor Company   \n",
      "40    41                            Bank of China   \n",
      "41    42                          Bank of America   \n",
      "42    43                           General Motors   \n",
      "43    44                          Elevance Health   \n",
      "44    45                                BMW Group   \n",
      "45    46                      Mercedes-Benz Group   \n",
      "46    47                           Meta Platforms   \n",
      "47    48   China Railway Construction Corporation   \n",
      "48    49                                    Baowu   \n",
      "49    50                                Citigroup   \n",
      "\n",
      "                         Industry Revenue (USD Billions)  \\\n",
      "0   Retail Information technology                    716   \n",
      "1                          Retail                    713   \n",
      "2                     Electricity                    545   \n",
      "3                     Oil and gas                    480   \n",
      "4                     Oil and gas                    476   \n",
      "5                     Oil and gas                    429   \n",
      "6          Information technology                    416   \n",
      "7          Information technology                    402   \n",
      "8                      Healthcare                    400   \n",
      "9                      Financials                    371   \n",
      "10                     Healthcare                    357   \n",
      "11                     Automotive                    348   \n",
      "12                    Oil and gas                    344   \n",
      "13                    Commodities                    331   \n",
      "14                    Oil and gas                    323   \n",
      "15                   Construction                    320   \n",
      "16                     Automotive                    312   \n",
      "17                     Healthcare                    308   \n",
      "18         Information technology                    281   \n",
      "19                     Healthcare                    262   \n",
      "20                    Commodities                    244   \n",
      "21                         Retail                    242   \n",
      "22                     Financials                    239   \n",
      "23                     Financials                    222   \n",
      "24                         Retail                    220   \n",
      "25                    Oil and gas                    218   \n",
      "26                    Commodities                    217   \n",
      "27                 Semiconductors                    215   \n",
      "28                    Oil and gas                    213   \n",
      "29                     Healthcare                    205   \n",
      "30                     Automotive                    204   \n",
      "31                    Oil and gas                    200   \n",
      "32                     Financials                    199   \n",
      "33                    Electronics                    198   \n",
      "34                    Electronics                    197   \n",
      "35                     Healthcare                    195   \n",
      "36                     Financials                    192   \n",
      "37                   Construction                    178   \n",
      "38                   Conglomerate                    177   \n",
      "39                     Automotive                    176   \n",
      "40                     Financials                    172   \n",
      "41                     Financials                    171   \n",
      "42                     Automotive                    171   \n",
      "43                     Healthcare                    171   \n",
      "44                     Automotive                    168   \n",
      "45                     Automotive                    165   \n",
      "46                   Social media                    164   \n",
      "47                   Construction                    160   \n",
      "48                          Steel                    157   \n",
      "49                     Financials                    156   \n",
      "\n",
      "   Profit (USD Billions)  Employees    Headquarters  \n",
      "0                   79.9  1,576,000   United States  \n",
      "1                   21.8  2,100,000   United States  \n",
      "2                    9.2  1,361,423           China  \n",
      "3                    106     73,311    Saudi Arabia  \n",
      "4                   25.2  1,026,301           China  \n",
      "5                    9.3    513,434           China  \n",
      "6                    112    166,000   United States  \n",
      "7                    132    190,820   United States  \n",
      "8                   14.4    400,000   United States  \n",
      "9                   88.9    392,400   United States  \n",
      "10                   8.3    259,500   United States  \n",
      "11                  17.9    684,025         Germany  \n",
      "12                  36.0     61,500   United States  \n",
      "13                  13.0      1,560     Switzerland  \n",
      "14                  19.3    103,000  United Kingdom  \n",
      "15                   4.2    382,894           China  \n",
      "16                  34.2    380,793           Japan  \n",
      "17                   3.0     48,000   United States  \n",
      "18                   101    228,000   United States  \n",
      "19                   1.7     44,000   United States  \n",
      "20                   7.3     12,479       Singapore  \n",
      "21                   6.2    316,000   United States  \n",
      "22                  49.5    309,926   United States  \n",
      "23                  51.4    419,252           China  \n",
      "24                   n/a    604,000         Germany  \n",
      "25                  21.3    102,579          France  \n",
      "26                   4.2     83,426     Switzerland  \n",
      "27                   120     36,000   United States  \n",
      "28                  15.2     79,400  United Kingdom  \n",
      "29                  0.26     47,520   United States  \n",
      "30                  20.1    258,275     Netherlands  \n",
      "31                  21.3     45,600   United States  \n",
      "32                  46.9    376,871           China  \n",
      "33                  11.0    267,860     South Korea  \n",
      "34                   4.5    621,393          Taiwan  \n",
      "35                   5.1     71,413   United States  \n",
      "36                  38.0    451,003           China  \n",
      "37                   2.1    314,149           China  \n",
      "38                  17.6    160,000   United States  \n",
      "39                   4.3    177,000   United States  \n",
      "40                  32.7    306,931           China  \n",
      "41                  26.5    212,985   United States  \n",
      "42                  10.1    163,000   United States  \n",
      "43                   5.9    104,900   United States  \n",
      "44                  12.2    154,950         Germany  \n",
      "45                  15.4    166,056         Germany  \n",
      "46                  62.3     78,450   United States  \n",
      "47                   1.7    336,433           China  \n",
      "48                   2.4    258,697           China  \n",
      "49                   9.2    237,925   United States  \n"
     ]
    }
   ],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import requests\n",
    "\n",
    "#Extract Website\n",
    "url = \"https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue\"\n",
    "headers = {\"User-Agent\": \"MyScraperApp/1.0 (contact@example.com)\"}\n",
    "\n",
    "page = requests.get(url, headers=headers)\n",
    "soup = BeautifulSoup(page.text, \"html.parser\")\n",
    " \n",
    "table = soup.find_all(\"table\")[0]      #extract necessary table\n",
    "\n",
    "\n",
    "#Extract Column Headings\n",
    "header_row = table.find(\"tr\")\n",
    "\n",
    "world_table_titles = [\n",
    "    title.text.strip() for title in header_row.find_all(\"th\")\n",
    "]\n",
    "\n",
    "\n",
    "#Extract Table Data\n",
    "column_data = table.find_all(\"tr\")\n",
    "scraped_data = []\n",
    "\n",
    "#tracker dictionary for active rowspans\n",
    "rowspan_tracker = {}\n",
    "\n",
    "#table rows past the header\n",
    "for row in column_data[2:]:\n",
    "  row_cells = row.find_all([\"th\", \"td\"])\n",
    "\n",
    "  if not row_cells:\n",
    "    continue\n",
    "\n",
    "  full_row = []\n",
    "  cell_idx = 0  #Pointer for HTML cells present in this row\n",
    "\n",
    "  #excluding state owned and refernces column\n",
    "  for col_idx in range(7):\n",
    "    #Case A: Check if this column position is currently active in a previous rowspan\n",
    "    if col_idx in rowspan_tracker:\n",
    "      value, remaining = rowspan_tracker[col_idx]\n",
    "      full_row.append(value)\n",
    "\n",
    "      #Decrement counter or remove if expired\n",
    "      if remaining - 1 > 0:\n",
    "        rowspan_tracker[col_idx] = (value, remaining - 1)\n",
    "      else:\n",
    "        del rowspan_tracker[col_idx]\n",
    "\n",
    "    #Case B: Standard cell extraction from HTML\n",
    "    elif cell_idx < len(row_cells):\n",
    "      cell = row_cells[cell_idx]\n",
    "      text = cell.text.strip()\n",
    "      full_row.append(text)\n",
    "\n",
    "      #Check if this cell initiates a new rowspan\n",
    "      rowspan = int(cell.get(\"rowspan\", 1))\n",
    "      if rowspan > 1:\n",
    "        rowspan_tracker[col_idx] = (text, rowspan - 1)\n",
    "\n",
    "      cell_idx += 1\n",
    "\n",
    "  #Add fully reconstructed row\n",
    "  if full_row:\n",
    "    scraped_data.append(full_row)\n",
    "\n",
    "\n",
    "#Build & Clean Pandas DataFrame\n",
    "df = pd.DataFrame(scraped_data, columns=world_table_titles[:7])\n",
    "\n",
    "df = df.rename(\n",
    "    columns={\n",
    "        \"Revenue\": \"Revenue (USD Billions)\",\n",
    "        \"Profit\": \"Profit (USD Billions)\",\n",
    "        \"Headquarters[note 1]\": \"Headquarters\",\n",
    "    }\n",
    ")\n",
    "\n",
    "#Display result and csv file creation, change your location as per requirement\n",
    "df.to_csv(r\"C:\\Users\\USER\\Documents\\8142\\data scrapper\\Largest_Companies.csv\", index=False)\n",
    "print(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e1f68ab8-d70b-4dd9-b7be-8372e10393d4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
